### PR TITLE
Fuzzy refactor pt 1

### PR DESCRIPTION
**Pull request by tmcw**
Approaches #15 - this is a tricky thing to conceptualize. I think, ideally, we would show recipes with stuff like

- Bourbon whiskey (whiskey)

And would consolidate the left side. All of the core functionality needs to change a bit in pedantic mode - compare neighbors loosely, show fuzzy categories, etc.

### CODE REVIEW

**Comment by wooorm** [comment]
> Bourbon whiskey (whiskey)

Yeah, agreed. That also helps with:

Screen Shot 2020-03-20 at 9 07 02 am

**Comment by wooorm** [comment]
For neighbors, I’d say that the algorithm should only count alcohol ingredients (spirits, liqueurs, fortifieds, bases) or optionally all fluids (alcohol and other fluids: syrup, juice). Swapping rum for gin is important, a lemon for an orange isn’t really that important...

**Comment by wooorm** [comment]
Great idea!

**Comment by tmcw** [comment]
Okay! I can still see a bunch of improvements I want to make, but this data representation seems pretty decent and works well - merging!

**Pull request merged**
